FROM node:16 as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY index.js ./

FROM node:16-alpine
WORKDIR /app
COPY --from=build /app ./
RUN adduser --disabled-password express
USER express

CMD ["node", "index.js"]
