FROM node:16
COPY . .
RUN useradd frontend && \
	npm install && npm install -g serve && \
	REACT_APP_BACKEND_URL='http://localhost/api' npm run build
USER frontend
CMD ["serve", "-s", "-l", "5000", "build"]
EXPOSE 5000
