version: '3.8'
services:
  simple_frontend:
    image: simple_frontend14
    ports:
      - "5000:5000"
    depends_on:
      - simple_backend
  simple_backend:
    image: simple_backend14
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=L33T_D3V0PS
    restart: unless-stopped
    depends_on:
      - redis
      - db
  redis:
      image: redis:alpine
      restart: unless-stopped
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=L33T_D3V0PS
#    container_name: db_redmine
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
volumes:
  database:
