version: '3.8'
services:
  simple_frontend:
    image: simple_frontend14
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/
    ports:
      - "5000:5000"
    depends_on:
      - simple_backend
  simple_backend:
    image: simple_backend14
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=L33T_D3V0PS
      - REQUEST_ORIGIN=*
    restart: unless-stopped
    depends_on:
      - redis
      - db
  redis:
      image: redis:alpine
      restart: unless-stopped
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=L33T_D3V0PS
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - simple_frontend

volumes:
  database:
