FROM node:16-alpine AS build
COPY . .
RUN npm install && \
    REACT_APP_BACKEND_URL='http://localhost/api' npm run build

FROM node:16-alpine

RUN adduser --disabled-password frontend  

COPY --from=build /build /app
WORKDIR /app

RUN npm install -g serve

USER frontend
CMD ["serve", "-s", "-l", "5000", "build"]
EXPOSE 5000
